name: Build APK

on:
  push:
    branches:
      - main  # Trigger the action when changes are pushed to the 'main' branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adoptopenjdk'

    - name: Set up Android SDK
      uses: react-native-community/github-actions/setup-android-sdk@v1

    - name: Build APK
      run: ./gradlew assembleRelease  # Use 'assembleDebug' for debug builds

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: fdroid-client-apk
        path: app/build/outputs/apk/release/app-release.apk  # Adjust the APK output path if necessary
